# Generated by Django 5.1.3 on 2025-08-28 12:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='price')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='compare at price')),
                ('cost_per_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='cost per item')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='barcode')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('track_quantity', models.BooleanField(default=True, verbose_name='track quantity')),
                ('continue_selling_when_out_of_stock', models.BooleanField(default=False, verbose_name='continue selling when out of stock')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], default='new', max_length=20, verbose_name='condition')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in grams', max_digits=10, null=True, verbose_name='weight')),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=10, null=True, verbose_name='height')),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in centimeters', max_digits=10, null=True, verbose_name='width')),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in centimeters', max_digits=10, null=True, verbose_name='length')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('categories', models.ManyToManyField(related_name='products', to='products.category', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='variant name')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product variant',
                'verbose_name_plural': 'product variants',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=128, verbose_name='alt text')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['position', 'created_at'],
                'unique_together': {('product', 'is_primary')},
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('size', 'Size'), ('color', 'Color'), ('material', 'Material'), ('style', 'Style')], max_length=50, verbose_name='option name')),
                ('value', models.CharField(max_length=100, verbose_name='option value')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product option',
                'verbose_name_plural': 'product options',
                'ordering': ['position'],
                'unique_together': {('product', 'name', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('comment', models.TextField(verbose_name='comment')),
                ('is_approved', models.BooleanField(default=False, verbose_name='is approved')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='is verified purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
