# Generated by Django 5.1.3 on 2025-08-28 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_daily_reports', models.BooleanField(default=True, verbose_name='enable daily reports')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, verbose_name='low stock threshold')),
                ('dashboard_refresh_interval', models.PositiveIntegerField(default=5, help_text='Set to 0 to disable auto-refresh', verbose_name='dashboard refresh interval (minutes)')),
                ('show_recent_orders', models.BooleanField(default=True, verbose_name='show recent orders')),
                ('show_sales_statistics', models.BooleanField(default=True, verbose_name='show sales statistics')),
                ('show_product_metrics', models.BooleanField(default=True, verbose_name='show product metrics')),
                ('show_customer_insights', models.BooleanField(default=True, verbose_name='show customer insights')),
            ],
            options={
                'verbose_name': 'Dashboard Settings',
                'verbose_name_plural': 'Dashboard Settings',
            },
        ),
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='date recorded')),
                ('total_products', models.PositiveIntegerField(default=0, verbose_name='total products')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='total orders')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total revenue')),
                ('total_customers', models.PositiveIntegerField(default=0, verbose_name='total customers')),
                ('pending_orders', models.PositiveIntegerField(default=0, verbose_name='pending orders')),
                ('completed_orders', models.PositiveIntegerField(default=0, verbose_name='completed orders')),
                ('low_stock_products', models.PositiveIntegerField(default=0, verbose_name='low stock products')),
                ('out_of_stock_products', models.PositiveIntegerField(default=0, verbose_name='out of stock products')),
            ],
            options={
                'verbose_name': 'Dashboard Metrics',
                'verbose_name_plural': 'Dashboard Metrics',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('widget_type', models.CharField(choices=[('recent_orders', 'Recent Orders'), ('sales_chart', 'Sales Chart'), ('top_products', 'Top Products'), ('revenue_stats', 'Revenue Statistics'), ('customer_activity', 'Customer Activity'), ('inventory_status', 'Inventory Status')], max_length=50, verbose_name='widget type')),
                ('is_visible', models.BooleanField(default=True, verbose_name='is visible')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='settings')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'ordering': ['position', 'title'],
            },
        ),
    ]
